version: '2'
services:
  m0:
    image: mongo:4.0.9-xenial
    container_name: m-master
    ports:
      - "27017:27017"
    command: --noprealloc --smallfiles --replSet rs1 --oplogSize 128
    volumes:
      - ~/docker/mongo/master:/data/db
    restart: always
  m1:
    image: mongo:4.0.9-xenial
    container_name: m-slave
    ports:
      - "27018:27017"
    command: --noprealloc --smallfiles --replSet rs1 --oplogSize 128
    volumes:
      - ~/docker/mongo/slave:/data/db
    restart: always
